name: Deploy to Azure

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout' 
      uses: actions/checkout@master
    
    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: 'Build and Test'
      run: |
        npm install
        npm run build ---if-present
        npm run test ---if-present
       
    - name: 'Deploy Azure Web App'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: calcjs
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
